const COMMON = {
    'LOADING_GIF': '/images/common/loading.gif',
  'SEARCH_SVG': '/images/common/search.svg',
  }
const HOME = {
    'ACTIVE_DOC_SVG': '/images/home/active-doc.svg',
  'ACTIVE_EMAIL_SVG': '/images/home/active-email.svg',
  'ACTIVE_LOGOUT_SVG': '/images/home/active-logout.svg',
  'ACTIVE_SWITCH_SVG': '/images/home/active-switch.svg',
  'ACTIVE_USER_SVG': '/images/home/active-user.svg',
  'ACTIVE_X_SVG': '/images/home/active-x.svg',
  'DEFAULT_USER_PNG': '/images/home/default-user.png',
  'DISCORD_SVG': '/images/home/discord.svg',
  'DOC_SVG': '/images/home/doc.svg',
  'EMAIL_SVG': '/images/home/email.svg',
  'FOOT_EMAIL_SVG': '/images/home/foot-email.svg',
  'LOGOUT_SVG': '/images/home/logout.svg',
  'MEDIUM_SVG': '/images/home/medium.svg',
  'ORDINAL_ICON_SVG': '/images/home/ordinal-icon.svg',
  'SWITCH_SVG': '/images/home/switch.svg',
  'TWITTER_SVG': '/images/home/twitter.svg',
  'USER_SVG': '/images/home/user.svg',
  'X_SVG': '/images/home/x.svg',
  }
const ICON = {
    'ACTIVE_SHARE_SVG': '/images/icon/active-share.svg',
  'ACTIVELINK_SVG': '/images/icon/activeLink.svg',
  'CLOSE_SVG': '/images/icon/close.svg',
  'COPY_SVG': '/images/icon/copy.svg',
  'DEFAULT_TICK_PNG': '/images/icon/default-tick.png',
  'DOWN_SVG': '/images/icon/down.svg',
  'ERROR_SVG': '/images/icon/error.svg',
  'ERROR_LIGHT_SVG': '/images/icon/error_light.svg',
  'HEY_SVG': '/images/icon/hey.svg',
  'LINK_SVG': '/images/icon/link.svg',
  'LOADING_SVG': '/images/icon/loading.svg',
  'LOGO_SVG': '/images/icon/logo.svg',
  'OKX_PNG': '/images/icon/okx.png',
  'SELECTED_SVG': '/images/icon/selected.svg',
  'SHARE_SVG': '/images/icon/share.svg',
  'SUCCESS_SVG': '/images/icon/success.svg',
  'TOP_SVG': '/images/icon/top.svg',
  'TWITTER_SVG': '/images/icon/twitter.svg',
  'UNISAT_PNG': '/images/icon/unisat.png',
  'WARN_SVG': '/images/icon/warn.svg',
  }
  export const Images = {
    COMMON,
  HOME,
  ICON,
  }
  